### ISSUE TITLE
标记这个仓库过期？

### ISSUE THREAD

**Issue by inclyc** [xmake-io/xmake-package-gentoo#11]
### Xmake 版本

不适用

### 操作系统版本和架构

不适用

### 描述问题

GURU已经合并了我们的patch到主线，这个仓库其实可以标记为过期了。然后在xmake doc里重新写一下Gentoo的安装

<img width="970" alt="截屏2022-09-06 11 42 12" src="https://user-images.githubusercontent.com/36667224/188542678-aac020e5-dfc0-4f0e-a7b6-b054314c7d20.png">

### 期待的结果

如图所示，现在用户可以从GURU安装xmake（一般Gentoo用户都有这个仓库）所以应该可以`Archive`这个仓库？

**Comment by waruqi** [comment]
已经进官方仓库了？那后续再哪里维护 gentoo 包脚本呢？文档上安装指令，你这帮忙更新下吧。。

**Comment by inclyc** [comment]
> 已经进官方仓库了？那后续再哪里维护 gentoo 包脚本呢？文档上安装指令，你这帮忙更新下吧。。

在准备PR了

**Comment by waruqi** [comment]
我看 https://github.com/gentoo/gentoo 这里没有进去么，guru 也是官方仓库吗，跟这个有什么关系，都是官方仓库？https://gitweb.gentoo.org/repo/proj/guru.git/tree/dev-util/xmake 我看这里进去了。。

**Comment by waruqi** [comment]
这里其实也有个很老的 pr ，https://github.com/gentoo/gentoo/pull/20841 一直没被 merge

**Comment by inclyc** [comment]
> 我看 https://github.com/gentoo/gentoo 这里没有进去么，guru 也是官方仓库吗，跟这个有什么关系，都是官方仓库？https://gitweb.gentoo.org/repo/proj/guru.git/tree/dev-util/xmake 我看这里进去了。。

有点像AUR 

Gentoo基于源码安装所以在gentoo/gentoo的和guru的没多大区别

Link: https://wiki.gentoo.org/wiki/Project:GURU

**Comment by inclyc** [comment]
> 这里其实也有个很老的 pr ，[gentoo/gentoo#20841](https://github.com/gentoo/gentoo/pull/20841) 一直没被 merge

Gentoo 官方仓库需要有一个认证的`Gentoo Developer`维护，比较麻烦，似乎希望`xmake`有多一点依赖再加进去，所以让我先加到GURU

**Comment by inclyc** [comment]
> 已经进官方仓库了？那后续再哪里维护 gentoo 包脚本呢？

在GURU提交就行，我可以负责维护版本更新

> 文档上安装指令，你这帮忙更新下吧。。

xmake.io 网站上似乎没写`Gentoo`相关的安装，我去写一个？

或者直接写在这个仓库？

**Comment by inclyc** [comment]
> Gentoo基于源码安装所以在gentoo/gentoo的和guru的没多大区别

因为两个仓库都只有安装脚本(ebuild)，不会有打包的二进制，装起来没AUR那么野

**Comment by inclyc** [comment]
> Gentoo基于源码安装所以在gentoo/gentoo的和guru的没多大区别

因为两个仓库都只有安装脚本(ebuild)，不会有打包的二进制，装起来没AUR那么野

**Comment by waruqi** [comment]
哦哦。那这里先暂时一起同步吧，慢点归档，即使这里不同步，也先放着吧，然后 README 里面可以贴上 [guru](https://gitweb.gentoo.org/repo/proj/guru.git/tree/dev-util/xmake) 的 link 

> xmake.io 网站上似乎没写Gentoo相关的安装，我去写一个？

文档站上更新吧。。https://xmake.io/#/guide/installation?id=other-linux 加一个 gentoo 项

**Comment by inclyc** [comment]
> 哦哦。那这里先暂时一起同步吧

好的

> 加一个 gentoo 项

在写了在写了
